export { default as Account } from './Account';
export { default as Dashboard } from './Dashboard';
export { default as NotFound } from './NotFound';
export { default as Subscribe } from './Subscribe';
export { default as Settings } from './Settings';
export { default as AllNotifications } from './AllNotifications/AllNotifications';
export { default as Starred } from './AllNotifications/Starred';
export { default as Unread } from './AllNotifications/Unread';
export { default as Testing } from './Testing';
